### ISSUE TITLE
onInsert 함수 에러

### ISSUE THREAD

**Issue by wwwalohacampus** [JongsikLEE01/DaEut_React#20]
ServiceInsert.jsx 에서
onInsert 함수호출 코드 실행 시 
함수 정의 안되어 있다는 에러

**Comment by JongsikLEE01** [comment]
넵 맞습니다 ㅜ props로 넘겨주는데도 인식을 못하는거같아요

**Comment by wwwalohacampus** [comment]
![2024-06-29 21 47 52](https://github.com/JongsikLEE01/DaEut_React/assets/53545071/283c422c-9853-427d-967b-e1266f060ad0)

**Comment by wwwalohacampus** [comment]
![image](https://github.com/JongsikLEE01/DaEut_React/assets/53545071/4a3bf982-1244-4c28-9819-3e6212324464)

다우나 종시기 import 실수함

극ㅎ
